# mongodb-secrets.yaml
#
# Ce fichier stocke les informations sensibles telles que le nom d'utilisateur et le mot de passe de MongoDB dans Kubernetes sous forme de Secret.

apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret  # Le nom du secret, utilisé pour le référencer dans le StatefulSet ou les autres configurations.
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==      # Nom d'utilisateur encodé en base64. (Ici "root")
  MONGO_INITDB_ROOT_PASSWORD: ZXhhbXBsZQ==  # Mot de passe encodé en base64. (Ici "example")
  MONGO_INITDB_DATABASE: dGVzdA==           # Nom de la base de données encodé en base64. (Ici "test")
  MONGO_URI: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBsb2NhbGhvc3Q6MjcwMTcvdGVzdD9hdXRoU291cmNlPWFkbWlu
