services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
        - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    command:
        - --auth
    networks:
        - backend
    volumes:
        - mongo_data:/data/db
    restart: always
    logging:
        driver: "json-file"
        options:
            max-size: "50m"
            max-file: "3"
