apiVersion: apps/v1
kind: Deployment
metadata:
  name: aegis-web-deployment
  labels:
    app: aegis-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aegis-web
  template:
    metadata:
      labels:
        app: aegis-web
    spec:
      containers:
      - name: aegis-web
        image: realdragonma/aegis-web:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"