apiVersion: apps/v1
kind: Deployment
metadata:
  name: pelliculum-web-deployment
  labels:
    app: pelliculum-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pelliculum-web
  template:
    metadata:
      labels:
        app: pelliculum-web
    spec:
      containers:
      - name: pelliculum-web
        image: your-docker-username/pelliculum-web:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"