apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restapi-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Ajustez selon les besoins de stockage de votre application
