# Ce fichier stocke les informations sensibles telles que le nom d'utilisateur et le mot de passe de MongoDB dans Kubernetes sous forme de Secret.

apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret  # Le nom du secret, utilisé pour le référencer dans le StatefulSet ou les autres configurations.
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: UGVsbGljdWx1bQ==      # Nom d'utilisateur encodé en base64. (Ici "Pelliculum")
  MONGO_INITDB_ROOT_PASSWORD: T0xaZjU0ZU9aVmp6NQ==  # Mot de passe encodé en base64. (Ici "OLZf54eOZVjz5")
  MONGO_INITDB_DATABASE: cGVsbGljdWx1bQ==           # Nom de la base de données encodé en base64. (Ici "pelliculum")
