name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Docker Buildx (required for multi-platform builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub (you will need to store credentials in GitHub secrets)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build the Docker image and tag it (replace with your Docker Hub username/repo)
    - name: Build and tag Docker image
      run: |
        docker build -t realdragonma/pelliculum-rest:latest ./services/rest
        docker tag realdragonma/pelliculum-rest:latest realdragonma/pelliculum-rest:${{ github.sha }}

    # Step 5: Push the Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push realdragonma/pelliculum-rest:latest
        docker push realdragonma/pelliculum-rest:${{ github.sha }}
